# Generated by Django 2.1.4 on 2019-02-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stencil'),
    ]

    operations = [
        migrations.AddField(
            model_name='stencil',
            name='layers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='stencil',
            name='stencil_name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
