# Generated by Django 2.1.4 on 2019-02-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190206_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='stencil',
            name='stencil_id',
            field=models.IntegerField(default=0),
        ),
    ]
