# Generated by Django 2.1.4 on 2019-02-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stencil_stencil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_cnt', models.IntegerField(default=0)),
                ('process_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ID_Manager',
        ),
    ]
