# Generated by Django 2.1.7 on 2019-02-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190206_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='stencil',
            name='ready',
            field=models.IntegerField(default=0),
        ),
    ]
